"""Metadata-only ToolSpecs for V1.5 capabilities exposed as internal tools.

Phase 1 is metadata only. ``handler_ref`` records the *intended* future adapter
path (module:function); the adapters themselves are NOT implemented yet, and no
tool is executed. Each adapter will be a thin wrapper over an existing V1.5
service — zero duplicated business logic (see docs/architecture/v2.md §3).
"""

from app.agent.models.tool_spec import (
    LatencyClass,
    RiskLevel,
    SideEffectType,
    ToolKind,
    ToolSpec,
)

_INTERNAL = ToolKind.INTERNAL


def internal_tool_specs() -> list[ToolSpec]:
    """All initial internal tool specs (fresh instances per call)."""
    return [
        ToolSpec(
            id="search_documents",
            name="Search Documents",
            kind=_INTERNAL,
            description=(
                "Semantic search over the user's ingested document chunks. "
                "Returns the most relevant chunks with page and score."
            ),
            tags=["documents", "retrieval"],
            capability_tags=["semantic_search", "documents", "rag"],
            keywords=["search", "find", "documents", "chunks", "semantic"],
            typical_user_questions=[
                "What does the document say about X?",
                "Find the section about pricing.",
            ],
            success_examples=["search_documents(query='refund policy', top_k=8)"],
            input_schema={
                "type": "object",
                "properties": {
                    "query": {"type": "string"},
                    "top_k": {"type": "integer"},
                    "document_id": {"type": "string"},
                    "page": {"type": "integer"},
                },
                "required": ["query"],
            },
            output_schema={"type": "object", "properties": {"hits": {"type": "array"}}},
            output_fields=["hits"],
            risk_level=RiskLevel.LOW,
            side_effects=SideEffectType.READ,
            requires_approval=False,
            handler_ref="app.agent.tools.internal.documents:search_documents",
            latency_class=LatencyClass.MEDIUM,
            cacheable=True,
            context_weight=1.0,
            evidence_priority=90,
        ),
        ToolSpec(
            id="get_document_summary",
            name="Get Document Summary",
            kind=_INTERNAL,
            description="Return the stored document-level summary for a document.",
            tags=["documents"],
            capability_tags=["summary", "documents"],
            keywords=["summary", "document", "overview"],
            typical_user_questions=["Summarize this document.", "Give me an overview."],
            input_schema={
                "type": "object",
                "properties": {"document_id": {"type": "string"}},
                "required": ["document_id"],
            },
            output_schema={"type": "object", "properties": {"summary": {"type": "string"}}},
            output_fields=["summary"],
            risk_level=RiskLevel.LOW,
            side_effects=SideEffectType.READ,
            requires_approval=False,
            handler_ref="app.agent.tools.internal.documents:get_document_summary",
            latency_class=LatencyClass.LOW,
            cacheable=True,
            evidence_priority=70,
        ),
        ToolSpec(
            id="get_page_summary",
            name="Get Page Summary",
            kind=_INTERNAL,
            description="Return all chunks for a specific page of a document.",
            tags=["documents"],
            capability_tags=["page", "documents"],
            keywords=["page", "summary", "document"],
            typical_user_questions=["Summarize page 3.", "What is on page 5?"],
            input_schema={
                "type": "object",
                "properties": {
                    "document_id": {"type": "string"},
                    "page": {"type": "integer"},
                },
                "required": ["page"],
            },
            output_schema={"type": "object", "properties": {"chunks": {"type": "array"}}},
            output_fields=["chunks"],
            risk_level=RiskLevel.LOW,
            side_effects=SideEffectType.READ,
            requires_approval=False,
            handler_ref="app.agent.tools.internal.documents:get_page_summary",
            latency_class=LatencyClass.LOW,
            cacheable=True,
            evidence_priority=75,
        ),
        ToolSpec(
            id="list_documents",
            name="List Documents",
            kind=_INTERNAL,
            description="List the user's uploaded documents and their status.",
            tags=["documents"],
            capability_tags=["list", "documents"],
            keywords=["list", "documents", "files", "uploads"],
            typical_user_questions=["What documents do I have?", "List my files."],
            input_schema={
                "type": "object",
                "properties": {"limit": {"type": "integer"}},
            },
            output_schema={"type": "object", "properties": {"documents": {"type": "array"}}},
            output_fields=["documents"],
            risk_level=RiskLevel.LOW,
            side_effects=SideEffectType.READ,
            requires_approval=False,
            handler_ref="app.agent.tools.internal.documents:list_documents",
            latency_class=LatencyClass.LOW,
            cacheable=False,
            evidence_priority=30,
        ),
        ToolSpec(
            id="get_thread_summary",
            name="Get Thread Summary",
            kind=_INTERNAL,
            description="Return the running summary for a conversation thread.",
            tags=["memory"],
            capability_tags=["summary", "conversation", "memory"],
            keywords=["thread", "summary", "conversation", "history"],
            typical_user_questions=["What have we discussed so far?"],
            input_schema={
                "type": "object",
                "properties": {"thread_id": {"type": "string"}},
                "required": ["thread_id"],
            },
            output_schema={"type": "object", "properties": {"summary": {"type": "string"}}},
            output_fields=["summary"],
            risk_level=RiskLevel.LOW,
            side_effects=SideEffectType.READ,
            requires_approval=False,
            handler_ref="app.agent.tools.internal.memory:get_thread_summary",
            latency_class=LatencyClass.LOW,
            cacheable=False,
            evidence_priority=60,
        ),
        ToolSpec(
            id="get_recent_messages",
            name="Get Recent Messages",
            kind=_INTERNAL,
            description="Return the most recent messages in a conversation thread.",
            tags=["memory"],
            capability_tags=["messages", "conversation", "memory"],
            keywords=["recent", "messages", "conversation", "history"],
            typical_user_questions=["What did I just ask?"],
            input_schema={
                "type": "object",
                "properties": {
                    "thread_id": {"type": "string"},
                    "limit": {"type": "integer"},
                },
                "required": ["thread_id"],
            },
            output_schema={"type": "object", "properties": {"messages": {"type": "array"}}},
            output_fields=["messages"],
            risk_level=RiskLevel.LOW,
            side_effects=SideEffectType.READ,
            requires_approval=False,
            handler_ref="app.agent.tools.internal.memory:get_recent_messages",
            latency_class=LatencyClass.LOW,
            cacheable=False,
            evidence_priority=80,
        ),
        ToolSpec(
            id="get_user_preferences",
            name="Get User Preferences",
            kind=_INTERNAL,
            description="Return the user's saved long-term preferences.",
            tags=["memory"],
            capability_tags=["preferences", "memory"],
            keywords=["preferences", "settings", "remember"],
            typical_user_questions=["What are my preferences?"],
            input_schema={
                "type": "object",
                "properties": {"limit": {"type": "integer"}},
            },
            output_schema={"type": "object", "properties": {"preferences": {"type": "array"}}},
            output_fields=["preferences"],
            risk_level=RiskLevel.LOW,
            side_effects=SideEffectType.READ,
            requires_approval=False,
            handler_ref="app.agent.tools.internal.memory:get_user_preferences",
            latency_class=LatencyClass.LOW,
            cacheable=False,
            evidence_priority=50,
        ),
        ToolSpec(
            id="save_user_preference",
            name="Save User Preference",
            kind=_INTERNAL,
            description="Persist a long-term user preference (a write operation).",
            tags=["memory"],
            capability_tags=["preferences", "memory", "write"],
            keywords=["remember", "save", "preference", "from now on"],
            typical_user_questions=[
                "Remember that I prefer concise answers.",
                "From now on, use metric units.",
            ],
            success_examples=["save_user_preference(text='I prefer concise answers')"],
            input_schema={
                "type": "object",
                "properties": {"text": {"type": "string"}},
                "required": ["text"],
            },
            output_schema={"type": "object", "properties": {"preference": {"type": "object"}}},
            output_fields=["preference"],
            risk_level=RiskLevel.MEDIUM,
            side_effects=SideEffectType.WRITE,
            requires_approval=False,
            idempotent=True,
            handler_ref="app.agent.tools.internal.memory:save_user_preference",
            latency_class=LatencyClass.LOW,
            cacheable=False,
            emit_audit=True,
            evidence_priority=10,
        ),
        ToolSpec(
            id="get_job_status",
            name="Get Job Status",
            kind=_INTERNAL,
            description="Return the status of a document ingestion job.",
            tags=["jobs"],
            capability_tags=["jobs", "status", "ingestion"],
            keywords=["job", "status", "ingestion", "processing"],
            typical_user_questions=["Is my document done processing?"],
            input_schema={
                "type": "object",
                "properties": {"job_id": {"type": "string"}},
                "required": ["job_id"],
            },
            output_schema={"type": "object", "properties": {"job": {"type": "object"}}},
            output_fields=["job"],
            risk_level=RiskLevel.LOW,
            side_effects=SideEffectType.READ,
            requires_approval=False,
            handler_ref="app.agent.tools.internal.jobs:get_job_status",
            latency_class=LatencyClass.LOW,
            cacheable=False,
            evidence_priority=20,
        ),
        ToolSpec(
            id="answer_from_context",
            name="Answer From Context",
            kind=_INTERNAL,
            description=(
                "Composite tool: run the V1.5 deterministic RAG pipeline to "
                "answer a question grounded in retrieved context."
            ),
            tags=["chat"],
            capability_tags=["answer", "rag", "composite"],
            keywords=["answer", "question", "chat", "grounded"],
            typical_user_questions=["Answer my question using my documents."],
            success_examples=["answer_from_context(question='...', document_id='...')"],
            input_schema={
                "type": "object",
                "properties": {
                    "question": {"type": "string"},
                    "thread_id": {"type": "string"},
                    "document_id": {"type": "string"},
                },
                "required": ["question"],
            },
            output_schema={"type": "object", "properties": {"answer": {"type": "string"}}},
            output_fields=["answer"],
            risk_level=RiskLevel.LOW,
            side_effects=SideEffectType.READ,
            requires_approval=False,
            data_egress=True,  # invokes the LLM provider under the hood
            handler_ref="app.agent.tools.internal.chat:answer_from_context",
            latency_class=LatencyClass.HIGH,
            cacheable=False,
            evidence_priority=40,
        ),
    ]
